### ISSUE TITLE
Sharing: iTerm2 color theme config file

### ISSUE THREAD

**Issue by unknowledgeable** [embark-theme/vim#12]
Here's the iTerm2 color theme file if you want that too

[Embark.itermcolors.zip](https://github.com/embark-theme/vim/files/5089462/Embark.itermcolors.zip) (zipped because github doesn't like the .itermcolors extension for some reason)

iTerm has a few extra colours for their featureset but I disabled them all to keep it strictly based on your reddit post colour names. Can change any and all if needed.

<img width="549" alt="Screenshot 2020-08-18 at 11 27 07" src="https://user-images.githubusercontent.com/43091756/90496177-cc039000-e145-11ea-92fd-01532acd4ac1.png">

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Ansi 0 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.19215686619281769</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.10980392247438431</real>
		<key>Red Component</key>
		<real>0.11764705926179886</real>
	</dict>
	<key>Ansi 1 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.60784316062927246</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.44313725829124451</real>
		<key>Red Component</key>
		<real>0.94117647409439087</real>
	</dict>
	<key>Ansi 10 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.57254904508590698</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.89803922176361084</real>
		<key>Red Component</key>
		<real>0.17254902422428131</real>
	</dict>
	<key>Ansi 11 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.47058823704719543</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.70196080207824707</real>
		<key>Red Component</key>
		<real>1</real>
	</dict>
	<key>Ansi 12 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.88627451658248901</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.62745100259780884</real>
		<key>Red Component</key>
		<real>0.11372549086809158</real>
	</dict>
	<key>Ansi 13 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.91764706373214722</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.25882354378700256</real>
		<key>Red Component</key>
		<real>0.65490198135375977</real>
	</dict>
	<key>Ansi 14 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.94509804248809814</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.94901961088180542</real>
		<key>Red Component</key>
		<real>0.38823530077934265</real>
	</dict>
	<key>Ansi 15 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.80000001192092896</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.70196080207824707</real>
		<key>Red Component</key>
		<real>0.65098041296005249</real>
	</dict>
	<key>Ansi 2 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.82745099067687988</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.93725490570068359</real>
		<key>Red Component</key>
		<real>0.63137257099151611</real>
	</dict>
	<key>Ansi 3 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.66666668653488159</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.91372549533843994</real>
		<key>Red Component</key>
		<real>1</real>
	</dict>
	<key>Ansi 4 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>1</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.78039216995239258</real>
		<key>Red Component</key>
		<real>0.34117648005485535</real>
	</dict>
	<key>Ansi 5 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.91764706373214722</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.57254904508590698</real>
		<key>Red Component</key>
		<real>0.78039216995239258</real>
	</dict>
	<key>Ansi 6 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.92156863212585449</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.87450981140136719</real>
		<key>Red Component</key>
		<real>0.52941179275512695</real>
	</dict>
	<key>Ansi 7 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.94901961088180542</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.97254902124404907</real>
		<key>Red Component</key>
		<real>0.97254902124404907</real>
	</dict>
	<key>Ansi 8 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.3490196168422699</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.21960784494876862</real>
		<key>Red Component</key>
		<real>0.24313725531101227</real>
	</dict>
	<key>Ansi 9 Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.43137255311012268</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.18039216101169586</real>
		<key>Red Component</key>
		<real>0.94117647409439087</real>
	</dict>
	<key>Background Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.19215686619281769</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.10980392247438431</real>
		<key>Red Component</key>
		<real>0.11764705926179886</real>
	</dict>
	<key>Badge Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>0.5</real>
		<key>Blue Component</key>
		<real>0.4117647111415863</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.20392157137393951</real>
		<key>Red Component</key>
		<real>0.80784314870834351</real>
	</dict>
	<key>Bold Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>1</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.78975206613540649</real>
		<key>Red Component</key>
		<real>0.76818817853927612</real>
	</dict>
	<key>Cursor Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.82745099067687988</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.93725490570068359</real>
		<key>Red Component</key>
		<real>0.63137257099151611</real>
	</dict>
	<key>Cursor Guide Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>0.047881155303030304</real>
		<key>Blue Component</key>
		<real>1</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>1</real>
		<key>Red Component</key>
		<real>1</real>
	</dict>
	<key>Cursor Text Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.19215686619281769</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.10980392247438431</real>
		<key>Red Component</key>
		<real>0.11764705926179886</real>
	</dict>
	<key>Foreground Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>1</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>1</real>
		<key>Red Component</key>
		<real>0.93333333730697632</real>
	</dict>
	<key>Link Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.63137257099151611</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.90588235855102539</real>
		<key>Red Component</key>
		<real>0.93725490570068359</real>
	</dict>
	<key>Selected Text Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.19215686619281769</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.10980392247438431</real>
		<key>Red Component</key>
		<real>0.11764705926179886</real>
	</dict>
	<key>Selection Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.98823529481887817</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.98823529481887817</real>
		<key>Red Component</key>
		<real>0.9843137264251709</real>
	</dict>
	<key>Tab Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.3490196168422699</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.21960784494876862</real>
		<key>Red Component</key>
		<real>0.24313725531101227</real>
	</dict>
	<key>Underline Color</key>
	<dict>
		<key>Alpha Component</key>
		<real>1</real>
		<key>Blue Component</key>
		<real>0.50694197416305542</real>
		<key>Color Space</key>
		<string>sRGB</string>
		<key>Green Component</key>
		<real>0.3795028030872345</real>
		<key>Red Component</key>
		<real>0.34893858432769775</real>
	</dict>
</dict>
</plist>
```

**Comment by pyrho** [comment]
@skbolton created an org for embark ! https://github.com/embark-theme, once he gets to creating a project for iTerm you could submit it there.

**Comment by pyrho** [comment]
Totally unrelated but I'm not sure where to ask this; I created a theme for [k9s](https://github.com/derailed/k9s) too, @skbolton if you could create a repo in the org for that too I'll submit a PR there 🙏 
Thanks.

It got me thinking that it might be a bit cumbersome to handle the themes for each app in a separate repos, food for thought.

**Comment by skbolton** [comment]
@pyrho There is a lot to figure out with the new organization. I don't mind adding a lot of ports, in fact I think it would be cool if the theme had very widespread usage in things. But I also don't want to drown in issues and tickets for things that I don't use or wouldn't know how to support. So far things have been going great and I am happy with the response my little vim theme has received! It also feels like I will have some good contributors who can help grow this theme. I do want to make sure that I take the time to organize things and set up the organization better and think through this stuff. I think anything beyond common terminals and vim/emacs things I might pump the brakes, only momentarily, while I catch up on thinking through how all this can grow.
To your comment about a whole repo being cumbersome for sharing a single file to configure something I agree. An idea I had is to create a site for the theme and have a page for each port, very similar to what dracula and nord does. With these pages it could be possible just to show the configuration file for the port so that users can copy it and go. Also it might be possible to automate these pages to always be up to date with the most recent palette. Like I said a lot to think about. Thanks for being active so far.

**Comment by skbolton** [comment]
@unknowledgeable for now I will create a repo for iterm that we can use for what you have here. But the lighter gray color (eclipse) in the theme has moved from to #3E3859 to #585273. Can you just make sure that change gets into the iterm palette.

**Comment by unknowledgeable** [comment]
@skbolton updated to reflect that change
[Embark.itermcolors.zip](https://github.com/embark-theme/vim/files/5092851/Embark.itermcolors.zip)
<img width="545" alt="Screenshot 2020-08-18 at 23 06 00" src="https://user-images.githubusercontent.com/43091756/90565574-69db7700-e1a7-11ea-86e7-daa83f31ea76.png">

That look better to you? Any opinions on the iTerm specific things like clickable link colours etc?

Also, similarly to @pyrho, not sure where to ask this but what do you think about adding a [bat](https://github.com/sharkdp/bat) theme? I use fzf.vim and a couple of other vim plugins that show bat previews and I'm not very happy with the base16/ansi-light/ansi-dark themes as they seem to conflict with the vim theme in that I get text that has the same colour as backgrounds etc. I've got little idea about how to create a syntax theme but willing to give it a go if it's useful.

> An idea I had is to create a site for the theme and have a page for each port, very similar to what dracula and nord does. With these pages it could be possible just to show the configuration file for the port so that users can copy it and go. Also it might be possible to automate these pages to always be up to date with the most recent palette. Like I said a lot to think about.

Sounds very cool, the dracula website is pretty sweet!

**Comment by pyrho** [comment]
> An idea I had is to create a site for the theme and have a page for each port, very similar to what dracula and nord does. 

Very cool indeed !

@unknowledgeable I'd also be interested in your bat/fzf themes :)

**Comment by unknowledgeable** [comment]
For fzf I just did this and it looks good to me, but I've literally just been hacking around without fully knowing what I'm doing trying to get it all to work on my setup, so it's pretty messy spaghetti on my end:

```
" Customize fzf colors to match your color scheme
 let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }
```
I also added this to make the fzf floating window border cyan instead of orange:

```
let g:fzf_layout = {'up':'~90%', 'window': { 'width': 0.8, 'height': 0.8,'yoffset':0.5,'xoffset': 0.5, 'highlight': 'Special', 'border': 'rounded' } }
```

I did have some trouble with getting the vim terminal colours to work and then work with fzf. Had to hardcode them for some reason (and I can't really remember why!) but if the above doesn't look good then maybe have a go at putting the following in to see if it works:
```
let g:terminal_color_0  = '#1E1C31'
let g:terminal_color_1  = '#F0719B'
let g:terminal_color_2  = '#A1EFD3'
let g:terminal_color_3  = '#FFE9AA'
let g:terminal_color_4  = '#57C7FF'
let g:terminal_color_5  = '#C792EA'
let g:terminal_color_6  = '#87DFEB'
let g:terminal_color_7  = '#F8F8F2'
let g:terminal_color_8  = '#585273'
let g:terminal_color_9  = '#F02E6E'
let g:terminal_color_10 = '#2CE592'
let g:terminal_color_11 = '#FFB378'
let g:terminal_color_12 = '#1DA0E2'
let g:terminal_color_13 = '#A742EA'
let g:terminal_color_14 = '#63F2F1'
let g:terminal_color_15 = '#A6B3CC'
```
As for the bat theme, I'm going to have to look into it in more detail.

**Comment by unknowledgeable** [comment]
@pyrho looks like it's[ a big faff ](https://github.com/sharkdp/bat/tree/master/assets)getting external themes working with bat, you have to make a sublime-text theme, use sublime to convert it to the correct format and then recompile bat with the new theme etc. Not sure if it's worth the effort it you have to do that every time you get an update. Unless I'm misunderstanding something there.

They seem to pull the official themes from the sublime themes in other repos though, not really sure how that all works.

Having `--theme="base16"` in `~/.config/bat/config` works on the aesthetic front, just different when it comes to syntax.

**Comment by skbolton** [comment]
For fzf themes I would suggest configuring it in your terminal. That way when you use it there or in vim the theme applies. I use skim mostly but a friend of mine who also uses embark as a theme has this in their rc.

```
export FZF_DEFAULT_OPTS=--color=fg:15,bg+:-1,fg+:-1,hl:01,info:07,prompt:06,pointer:06
```

**Comment by smithbm2316** [comment]
@skbolton I have used @unknowledgeable 's iTerm theme to move the colors into a json file: [embark-json.zip](https://github.com/embark-theme/vim/files/5115213/embark-json.zip) for convenience. I am using it to update my Windows Terminal theme. If the colors here are correct and it would be helpful for you, I'd be happy to upload a Windows Terminal colorScheme for people using the new Windows Terminal like myself! Love what you've done with the theme and am enjoying using it as I am currently trying to learn Vim for the first time :)

**Comment by skbolton** [comment]
@unknowledgeable @smithbm2316 for now I will create separate repos for you to make PR's against. At some point down the line I will archive those repos when I have the site up and running. 

My plan for ports that are just a simple file that needs to be copied and pasted, like terminal themes, is to just have them published as part of the site. I need to package up the palette and then write the logic that produces each ports page. Then down the line updating the palette and publishing will help keep a lot of the ports up to date.

**Comment by skbolton** [comment]
Repos created closing this

@unknowledgeable @smithbm2316 Can you both help me out and be sure to include screenshots in your PRs? Only rule so far is that screenshot only shows the system and no desktop elements. Thanks guys!

**Comment by smithbm2316** [comment]
>for now I will create separate repos for you to make PR's against. At some point down the line I will archive those repos when I have the site up and running.
 
>Can you both help me out and be sure to include screenshots in your PRs? Only rule so far is that screenshot only shows the system and no desktop elements. Thanks guys!

Thanks for creating the repos! I will go ahead and add a PR for the Windows Terminal theme (along with a screenshot) within the next day and a half. Ended up having a busy week of work so I'm catching up on a bunch of tasks on my to do list today and tomorrow.

**Comment by unknowledgeable** [comment]
Apologies for the delay, had a busy week and had to properly learn git and github to do this so was a bit slow to get going! Hope the PR is ok!
