### ISSUE TITLE
Image processor - suggestion for if and when you make a website

### ISSUE THREAD

**Issue by unknowledgeable** [embark-theme/vim#14]
Not sure where to post suggestions and ideas for things like this but thought this was too cool to not make you aware of.

I just found [this image processig tool](https://ign.schrodinger-hat.it/) someone's made for the Nord theme and thought it was pretty awesome. It basically applies the nord palette to any image you give it. Source is all on github so I thought if you do get round to making a Nord/Dracula style site, this would be an awesome /r/vimporn /r/unixporn feature!

**Comment by unknowledgeable** [comment]
Here's an example of an image processed with some of the Embark colours.

![scraper_processed](https://user-images.githubusercontent.com/43091756/92317001-9be83800-eff3-11ea-9042-304a684d931f.jpg)

**Comment by skbolton** [comment]
This is really awesome. I am going to have to play around with some photos. I like having a space theme so I might try some space photos

**Comment by skbolton** [comment]
I think I have decided to go a different direction. For now the site is going to be really simple. I'll upgrade it over time. It's live at https://embark-theme.github.io. Let me know what you think!

**Comment by unknowledgeable** [comment]
Love the simplicity! Looks great so far! I also really like how clean it is as I'm finding myself getting more and more annoyed with websites making everything move around or menus taking up half my screen when I just wanted to scroll away from it. 

I assume you're planning to do some of the following but I'd like to see:

- screenshots/examples of the ports
- some way of showing examples of common languages for the syntax on the vim theme, maybe a toggle or something
- descriptions of the colours for their recommended uses (e.g. error, warning, correct, background, foreground, cursor, highlight etc...)
- upcoming ports section

**Comment by skbolton** [comment]
Yes to all of the above
