### ISSUE TITLE
Question: What is the font used in README screenshot?

### ISSUE THREAD

**Issue by day4me** [embark-theme/vim#16]
I really like the font used in this screenshot https://github.com/embark-theme/vim/blob/master/embark-screenshot.png 
Can someone tell me what's the name of this font?

**Comment by tom-on-the-internet** [comment]
I believe it's Operator Mono. A paid font.

**Comment by skbolton** [comment]
Yes it is operator mono patched with ligatures.

**Comment by day4me** [comment]
Thank you
