### ISSUE TITLE
Include Color Pallette to Expand to other Softwares

### ISSUE THREAD

**Issue by Mastermind497** [embark-theme/vim#19]

**Comment by skbolton** [comment]
Yeah this is a work in progress. I want to eventually have a link to the theme site where all the ports can be displayed and the color palette can be displayed. But until then I suppose I could add a palette section to this repo.

**Comment by skbolton** [comment]
Its no where near remotely done but I have the theme site available here. https://embark-theme.github.io/
My goal is to have a place to show off the different ports and the palette. There will also be some guides and helpful stuff around how to use the palette effectively - which should also make porting easier.
