### ISSUE TITLE
embark not found

### ISSUE THREAD

**Issue by j0ker70** [embark-theme/vim#22]
I have installed embark using vim-plug. I have put it inside my vimrc. But everytime I open vim, it shows this error

```
Error detected while processing /home/pial/.vim/vimrc:
line    9:
E185: Cannot find color scheme 'embark'
Press ENTER or type command to continue
```

But, when I am inside vim, and then use the command mode to select embark as my colorscheme, then it works. 

My .vimrc file:

```
autocmd! bufwritepost vimrc ++nested source %


" change leader key to <space>, previously it was <alt>
let mapleader = " "


" colorscheme
colorscheme embark

" setting linenumbers and relative line numbers
set nu rnu

" incremental searching for vim
set incsearch

" shows command in the status bar
set showcmd

" Plugins installed using vim-plug
call plug#begin('~/.vim/plugged')

Plug 'embark-theme/vim', { 'as': 'embark' }

call plug#end()

```

I am using VIm 8.1 and my OS is Ubuntu 20.04.

**Comment by skbolton** [comment]
Did you close this because you resolved it?

**Comment by j0ker70** [comment]
> Did you close this because you resolved it?

Yes, here's the solution: https://vi.stackexchange.com/a/27467/23558
