### ISSUE TITLE
Disabling italics

### ISSUE THREAD

**Issue by reobin** [embark-theme/vim#24]
Hi!

I've been using the color scheme for the past weeks, and absolutely love it, but I can't seem to disable italics.
Is `let g:embark_terminal_italics = 0` supposed to work? Or is there a more specific option to disable italicized comments for example?

Thanks

**Comment by skbolton** [comment]
Crazy timing, I just discovered last night that this isn’t working. I ported the ability to toggle italics from another repo and apparently it didn’t handle it the best. Hang tight I’ll try to fix this during the weekend.

**Comment by skbolton** [comment]
Actually @reobin can you help me by testing out the `italics-fix` branch and see if it fixes the issue for you? You should only need to have that `g:embark_terminal_italics = 0` line you mentioned previously for it to work. I tested locally but I always prefer to get confirmation on others systems first.

**Comment by reobin** [comment]
@skbolton Works perfectly on my end both in and out of tmux.

I'll keep using that branch until the fix is live.

Thanks for the quick response!

**Comment by skbolton** [comment]
Merging now
