### ISSUE TITLE
[Question] What font do you use in your screenshots?

### ISSUE THREAD

**Issue by kryzar** [embark-theme/vim#33]
Hi,

What font are you using in your screenshots, for example [here](https://github.com/embark-theme/vim/blob/master/embark-screenshot.png)?

Thanks!

**Comment by skbolton** [comment]
I use [kitty](https://sw.kovidgoyal.net/kitty/index.html) as my terminal (there's also an embark theme for it). One of my favorite features is the font support. It allows you to define a specific font for every font style (bold, italic, etc) but also a fallback font for certain unicode ranges. So I am using a lot of fonts here. I have [roboto mono nerd font](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/RobotoMono/Regular/complete/Roboto%20Mono%20Nerd%20Font%20Complete.ttf) to give me the icons.  Then for the comments I use the italic version of [Operator Mono](https://www.typography.com/fonts/operator/styles). And just regular Operator mono for all other text.

Operator Mono is a paid font and it costs 200! I bought it years ago so the shock has worn off and I love it. But if you want free alternative I'd look at [IBM Plex](https://www.ibm.com/plex/). Or a much closer but $40 option is [Dank Mono](https://gumroad.com/l/dank-mono)

Here is my kitty config with the font handling lines https://github.com/skbolton/titan/blob/4abcbf07b9ac6cb95d90cbb2b19f3f00eb42e591/kitty/kitty/kitty.conf#L22-L30

**Comment by skbolton** [comment]
Feel free to ask any other questions but I will close this for now

**Comment by kryzar** [comment]
Thanks a lot for this detailed answer!
