### ISSUE TITLE
Wrong colors on Ubuntu in Windows Terminal (WSL)

### ISSUE THREAD

**Issue by ashrasmun** [embark-theme/vim#41]
Hey,

I just installed NeoVim (v0.4.3) and installed the embark theme. I'm using Ubuntu 20.04 LTS inside the Windows Terminal. After invoking `:colorscheme embark` the colors are different from what they should be.

![image](https://user-images.githubusercontent.com/12000269/129772292-0eccd1d8-30db-4382-84e0-63140c43411e.png)

I'm using it already inside GVim and I'm loving it, thank you for your work! 😊

**Comment by skbolton** [comment]
What terminal are you using? Looks like either termguicolors isn't turned on or the terminal doesn't support 24but color

**Comment by ashrasmun** [comment]
I tried using `xterm`, `xterm-256colors`, `xterm-24bit`, `source-256colors`, but all in all, I think I just don't understand how to setup the terminal properly, as when I invoke https://github.com/tmux/tmux/blob/master/tools/24-bit-color.sh I get a blank black space. 
![image](https://user-images.githubusercontent.com/12000269/131230871-b993bc0a-1ccc-478e-9504-933324fc6b00.png)

At least 256 colors work... Sorry for the hassle. It's not a problem with the colorscheme.

**Comment by skbolton** [comment]
Yeah embark hasn't been back ported to work with 256 colors well. I would suggest going with a terminal that supports 24 bit color such as alacritty or kitty terminal. Once you have that and termguicolors on in (n)vim it should work fine.

**Comment by ashrasmun** [comment]
Just in case someone finds this thread in the future:

- Lack of colors is a result on Windows Terminal quirk, where `:` cannot be used as a separator, but instead `;` must be used (https://github.com/microsoft/terminal/issues/11075#issuecomment-907702184)
- To enable support of 24-bit colors, I had to add `set termguicolors` to my `.vimrc`

Thanks for help!
