### ISSUE TITLE
Zathura Port

### ISSUE THREAD

**Issue by gdnand** [embark-theme/vim#42]
I have made a zathura port for this awesome colorscheme, Please check that out if you want to add a zathura port.
https://github.com/gdnand/zathura-embark-theme.git
Thanks!

**Comment by gdnand** [comment]
I have made a repo complying with your requests,
I can't open a pull request since it's empty:
[Here's the repo](github.com/gdnand/zathura)

**Comment by skbolton** [comment]
Sorry forgot to to add the initial commit. It's fully ready now
