### ISSUE TITLE
Support for lualine

### ISSUE THREAD

**Issue by Varal7** [embark-theme/vim#46]
Hi,

Love the embark theme.
Could we support https://github.com/nvim-lualine/lualine.nvim?
There is already a PR closed there: https://github.com/nvim-lualine/lualine.nvim/pull/269.

Thanks

**Comment by skbolton** [comment]
Yeah feel free to open a or here for that.

**Comment by skbolton** [comment]
@Varal7 I am going to close this issue. Feel free to open a PR for this.
