### ISSUE TITLE
Possible error in embark.vim

### ISSUE THREAD

**Issue by unbeschwert** [embark-theme/vim#53]
Hi,

Recently I updated my plugins in neovim and I received an error "Illegal value underdash" when I reopened neovim. 

The line [call s:h("DiffText",      {"bg": s:diff_changed, "gui": "underdash"})](https://github.com/embark-theme/vim/blob/57f05ba5fb821573788a5a9d9e888f780c79f68f/colors/embark.vim#L201) appears to be cause. 

Perhaps you meant to write 'underline' here ?

**Comment by skbolton** [comment]
Apologies, `underdash` is an option for me but this could be a situation where it is not cross compatible. Will merge fix for this.
