### ISSUE TITLE
Background is black

### ISSUE THREAD

**Issue by zbraniecki** [embark-theme/vim#56]
I have nushell+zellij+alacritty+neovim config on MacOS and when I switch to this theme the background of my neovim becomes pitch black which makes the colors stand out very aggressively.

How do I fix that?

**Comment by skbolton** [comment]
This issue almost always comes down to 24bit color support.

1. Your terminal must support it
2. If you use a multiplexer you have to tell it to turn that feature on
3. In (n)vim you then tell it to turn that on

For your setup
1. Alacritty should support it out of the box so I think you are good there
2. I have no idea on Zellij - I use tmux and could only give advice on setting up in that
3. n(vim) you need to turn on guicolors `vim.opt.termguicolors = true`


If anything previous in the chain isn't configured there is nothing that nvim can do about it. My suggestion is look into people talking about this in the Zellij community and you should have your fix.

**Comment by skbolton** [comment]
In Zellij what is your `$TERM` environment variable set to?

**Comment by skbolton** [comment]
You can also run this helper script

```bash
curl -s https://gist.githubusercontent.com/lifepillar/09a44b8cf0f9397465614e622979107f/raw/24-bit-color.sh >24-bit-color.sh
bash 24-bit-color.sh
```

I would run it at every level and make sure you get a smooth gradient of color. So alacritty without zellij, then in zellij, then in neovim without zellij, etc. It should show you where in the chain you have an issue.

**Comment by zbraniecki** [comment]
Setting `set termguicolors` in init.vim resolved the issue for me. Thank you!
