### ISSUE TITLE
improvement in MD files

### ISSUE THREAD

**Issue by luanlouzada** [embark-theme/vim#62]
![image](https://github.com/embark-theme/vim/assets/127630534/c8546f11-16e5-4272-974e-24b8f89149d1)

I find this theme amazing, but I'd like to open a discussion, and try to understand, if possible also get some help to fix or maybe improve this theme.

In MD files, out of nowhere, it puts letters in white instead of continuing in red, and it's very random.

**Comment by skbolton** [comment]
The characters should be in white. What you see in red here are the spell check errors. You can confirm this by calling `:set nospell` and seeing everything going back to white.

**Comment by luanlouzada** [comment]
You're right, I thought it was something to do with LSP and my marksman, but I looked into it and couldn't find anything, thank you very much.

The next step will be to configure a Portuguese spellchecker.

I believe I can close this issue now

**Comment by skbolton** [comment]
`:set dictionary?` will print out the current dictionary path its using. I am not sure if this is something you edit directly or not. But I am guessing there will be more details in `:help dictionary`
