### ISSUE TITLE
Add support for config italics and bold.

### ISSUE THREAD

**Issue by brunoferromega** [embark-theme/vim#70]
Could you add support for edit some text/syntax styles into embark-theme ?
I guess something like that it's a good solution ->

![Screenshot from 2024-06-28 21-50-19](https://github.com/embark-theme/vim/assets/87425146/c77b155e-62e7-4a8d-bdb0-803f5f636c3e)

e.g. : link for theme above -> https://github.com/mellow-theme/mellow.nvim

**Comment by skbolton** [comment]
Out of curiosity what things are you trying to toggle bold/italic on or off for?

**Comment by brunoferromega** [comment]
Well, I would like to functions and boolenas in italic - keywords and macros in italic and bold, because in general I think it looks good when we have syntax details in outstanding.

**Comment by skbolton** [comment]
I would like to avoid too many configuration options. Especially since it is quite easy to do this sort of customizing with vimscript/lua. After setting the embark theme you can always supply styling overrides. Example using lua.

```lua
vim.cmd('colorscheme embark')
vim.cmd('hi @function gui=italic')
vim.cmd(hi @keyword gui=bold')
```

Have you tried this approach?

**Comment by brunoferromega** [comment]
Nice, I didn't know that. 
I'll try, thank you for the attention.

**Comment by skbolton** [comment]
Sounds good I'll close this for now.
