### ISSUE TITLE
g:terminal_color_8 too dark

### ISSUE THREAD

**Issue by pyrho** [embark-theme/vim#9]
👋 ,

I'm not really sure how this color  thing works, but the 8th terminal color is a bit too dark to be usable, I'm not sure if  this issue is specific to my setup or not, maybe you can shed some light.

See the following screenshot:
<img width="1679" alt="Screenshot 2020-08-18 at 01 28 44" src="https://user-images.githubusercontent.com/145502/90454107-93869680-e0f2-11ea-9176-2fdcd3e4cfb5.png">
(on the left, `:terminal` with embark colors, the blackened text is barely visible; on the right a terminal not running in nvim)

Let me know if it makes sense, and if so I'd be happy  to submit a pull request.

The following patch fixes the issue:
```
diff --git a/colors/embark.vim b/colors/embark.vim
index 74a9e2c..3c4417d 100644
--- a/colors/embark.vim
+++ b/colors/embark.vim
@@ -344,7 +344,7 @@ let g:terminal_color_4 = s:blue.gui
 let g:terminal_color_5 = s:purple.gui
 let g:terminal_color_6 = s:cyan.gui
 let g:terminal_color_7 = s:space.gui
-let g:terminal_color_8 = s:subtle_black.gui
+let g:terminal_color_8 = s:bg_subtle.gui
 let g:terminal_color_9 = s:dark_red.gui
 let g:terminal_color_10 = s:dark_green.gui
 let g:terminal_color_11 = s:dark_yellow.gui
```

**Comment by unknowledgeable** [comment]
I agree with you on this. I've changed that color to `#8478BE` in my terminal config (not an official embark color, just used the brightness slider in HSB to get to something I thought worked).

@skbolton what are your thoughts?

**Comment by skbolton** [comment]
@pyrho I think that `bg_subtle` makes a lot of sense there. Especially since it's contrast was bumped recently. Feel free to do a PR. or I can get to it by the weekend.

**Comment by pyrho** [comment]
👋 ,

Just updated to the latest version and it seems this change has been reverted in https://github.com/embark-theme/vim/commit/406a29ca72eb6c85495fbb92856a6bcd4f51b043 `Fix terminal colors use old palette color`
What happened ? (:

**Comment by skbolton** [comment]
@pyrho sorry this keeps happening to you. I don't have a way in my setup to test this well. I did a big overhaul of the theme and this seems to have gotten reverted. I will push a fix now

**Comment by skbolton** [comment]
It will be a different color than before, let me know if its contrast is better.

**Comment by pyrho** [comment]
@skbolton no worries! Just updated, it looks perfect thanks for the quick update.
